import os
import re
from groq import Groq
from dataclasses import dataclass
from typing import List, Optional
from modules.github_reader import IssueData
from modules.code_parser import ParsedCode, ClassInfo
from dotenv import load_dotenv

load_dotenv()

@dataclass
class PatchResult:
    """The fix generated by the LLM."""
    filepath: str
    class_name: str
    original_code: str
    patched_code: str
    explanation: str
    confidence: str  # "high", "medium", "low"


class PatchGenerator:
    def __init__(self):
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError("GROQ_API_KEY not found in .env")
        self.client = Groq(api_key=api_key)
        self.model = "llama-3.3-70b-versatile"

    def generate(self, issue_data: IssueData, parsed: ParsedCode) -> List[PatchResult]:
        """
        Main entry point.
        For each suspicious class, ask the LLM to generate a fix.
        """
        print("\n[Patch Generator] Sending code to Groq for analysis...")
        results = []

        # Only patch source files, not test files
        source_classes = [
            cls for cls in parsed.suspicious_classes
            if not cls.name.startswith("Test") and "test" not in cls.filepath.lower()
        ]

        for cls in source_classes:
            print(f"\n[Patch Generator] Analyzing {cls.name} in {cls.filepath}...")
            result = self._generate_patch(issue_data, cls, parsed.issue_keywords)
            if result:
                results.append(result)

        return results

    def _generate_patch(
        self,
        issue_data: IssueData,
        cls: ClassInfo,
        keywords: List[str]
    ) -> Optional[PatchResult]:
        """Ask Groq to fix a specific class."""

        prompt = f"""You are an expert Python developer fixing a real GitHub bug.

## Issue Title
{issue_data.issue_title}

## Issue Description
{issue_data.issue_body[:500]}

## Class to Fix: `{cls.name}` in `{cls.filepath}`
```python
{cls.source[:3000]}
```

## Your Task
1. Identify the exact bug in this class related to the issue
2. Write the COMPLETE fixed version of only the buggy method(s)
3. Do NOT rewrite the entire class — only fix what's broken

## Response Format (follow this EXACTLY)

EXPLANATION:
[one paragraph explaining what the bug is and why your fix works]

CONFIDENCE: [high/medium/low]

FIXED_METHOD:
```python
[paste only the fixed method(s) here, complete and runnable]
```
"""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a senior Python engineer. You fix bugs precisely and minimally. Never rewrite code that isn't broken."
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.1,  # low temperature = more deterministic fixes
                max_tokens=2000
            )

            raw = response.choices[0].message.content
            return self._parse_response(raw, cls)

        except Exception as e:
            print(f"[Patch Generator] Groq API error: {e}")
            return None

    def _parse_response(self, raw: str, cls: ClassInfo) -> Optional[PatchResult]:
        """Extract structured fields from LLM response."""
        try:
            # Extract EXPLANATION
            explanation = ""
            exp_match = re.search(r"EXPLANATION:\s*(.+?)(?=CONFIDENCE:|FIXED_METHOD:|$)", raw, re.DOTALL)
            if exp_match:
                explanation = exp_match.group(1).strip()

            # Extract CONFIDENCE
            confidence = "medium"
            conf_match = re.search(r"CONFIDENCE:\s*(high|medium|low)", raw, re.IGNORECASE)
            if conf_match:
                confidence = conf_match.group(1).lower()

            # Extract FIXED_METHOD code block
            code = ""
            code_match = re.search(r"FIXED_METHOD:\s*```python\s*(.+?)```", raw, re.DOTALL)
            if code_match:
                code = code_match.group(1).strip()
            else:
                # Fallback: grab any python code block
                code_match = re.search(r"```python\s*(.+?)```", raw, re.DOTALL)
                if code_match:
                    code = code_match.group(1).strip()

            if not code:
                print(f"[Patch Generator] Warning: No code found in response for {cls.name}")
                print(f"[Patch Generator] Raw response:\n{raw[:500]}")
                return None

            return PatchResult(
                filepath=cls.filepath,
                class_name=cls.name,
                original_code=cls.source,
                patched_code=code,
                explanation=explanation,
                confidence=confidence
            )

        except Exception as e:
            print(f"[Patch Generator] Parse error: {e}")
            return None